steps:
  - name: bash
    id: CreateEnvFile
    entrypoint: bash
    args:
      - -c
      - |
        # Start with empty .env file
        > .env

        # Read each line from secrets_name.txt and add to .env file
        while read -r secret_name; do
          # Skip empty lines or comments
          [[ -z "$secret_name" || "$secret_name" =~ ^# ]] && continue
          
          # Convert the secret name to the Cloud Build substitution variable format
          # For example, MONGODB_URI becomes $_MONGODB_URI
          substitution_var="_$secret_name"
          
          # Access the value using indirect reference
          eval "value=\$${substitution_var}"
          
          # Add to .env file
          echo "$secret_name=$value" >> .env
          
          # Optional: Add debug info (won't show actual values)
          echo "Added $secret_name to .env file"
             done < infrastructure/cloud_build/secrets_name.txt

        echo "Created .env file with $(grep -c '=' .env) environment variables"
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - "-t"
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:latest
      - "-f"
      - infrastructure/cloud_build/Dockerfile
      - "."
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:latest
    id: PushLatest
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - >-
        --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:latest
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _TRIGGER_ID: cb3f172b-1064-4e29-a443-bef607389d6b
  _PLATFORM: managed
  _SERVICE_NAME: futbol-domingos-2
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_PROJECT_ID: futbol-app-451918
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - futbol-domingos-2
