steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - "-t"
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:latest
      - "-f"
      - infrastructure/cloud_build/Dockerfile
      - "--build-arg"
      - MONGODB_URI=$_MONGODB_URI
      - "--build-arg"
      - GCP_PROJECT_ID=$_GCP_PROJECT_ID
      - "--build-arg"
      - GCP_CLIENT_EMAIL=$_GCP_CLIENT_EMAIL
      - "--build-arg"
      - GCP_PRIVATE_KEY=$_GCP_PRIVATE_KEY
      - "--build-arg"
      - REDIS_HOST=$_REDIS_HOST
      - "--build-arg"
      - REDIS_PORT=$_REDIS_PORT
      - "--build-arg"
      - REDIS_PASSWORD=$_REDIS_PASSWORD
      - "--build-arg"
      - REDIS_USERNAME=$_REDIS_USERNAME
      - "--build-arg"
      - PUSHER_APP_ID=$_PUSHER_APP_ID
      - "--build-arg"
      - PUSHER_KEY=$_PUSHER_KEY
      - "--build-arg"
      - PUSHER_SECRET=$_PUSHER_SECRET
      - "--build-arg"
      - PUSHER_CLUSTER=$_PUSHER_CLUSTER
      - "--build-arg"
      - NEXT_PUBLIC_PUSHER_KEY=$_NEXT_PUBLIC_PUSHER_KEY
      - "--build-arg"
      - NEXT_PUBLIC_PUSHER_APP_ID=$_NEXT_PUBLIC_PUSHER_APP_ID
      - "."
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:latest
    id: PushLatest
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - >-
        --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:latest
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _TRIGGER_ID: cb3f172b-1064-4e29-a443-bef607389d6b
  _PLATFORM: managed
  _SERVICE_NAME: futbol-domingos
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_PROJECT_ID: futbol-app-451918
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - futbol-domingos
